# Generated by Django 3.1.7 on 2021-03-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=15, unique=True)),
                ('max_passengers', models.IntegerField()),
                ('year_of_manufacture', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first class', 'First Class')], default='business', max_length=30)),
                ('motor_type', models.CharField(choices=[('hybrid', 'Hybrid'), ('electric', 'Electric')], default='hybrid', max_length=40)),
            ],
        ),
    ]
