# Generated by Django 3.1.7 on 2021-04-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first class', 'First Class')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='motor_type',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=40),
        ),
    ]
