# Generated by Django 3.1.7 on 2021-04-02 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_delete_default_car_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='max_passengers',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Max passengers value is to low. Min: 1'), django.core.validators.MaxValueValidator(60, 'Max passengers value is to high. Max: 60')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 \\.\\-]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886, message='Manufacture year is to low. Min: 1886'), django.core.validators.MaxValueValidator(2021, message='Manufacture year is to high. Max: 2021')]),
        ),
    ]
