# Generated by Django 3.1.7 on 2021-04-03 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0003_car_fields_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first class', 'First Class')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='motor_type',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('electric', 'Electric')], default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(default=None, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 \\.\\-]{3,}$')]),
        ),
    ]
